# This file defines the different types of taxonomies in Bolt. See the 
# documentation for details: http://docs.bolt.cm/taxonomies#taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    listing_template: tag-listing.twig #custom template

chapters:
    slug: chapters
    singular_slug: chapter
    behaves_like: grouping
    has_sortorder: true
    options: { 'editors': 'Content editors', 'frontenders': 'Frontend developers',  'backenders': 'Backend developers' }

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ news, events, movies, music, books, life, love, fun ]

slidechapters:
    slug: slidechapters
    singular_slug: slidechapter
    behaves_like: grouping
    options: { main: "Slideshow homepage"}
    has_sortorder: true
